name: Deploy to GitHub Pages

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Build Jekyll Site
              run: jekyll build -d _site

            - name: Upload artifact
              uses: actions/upload-artifact@v2
              with:
                  name: my-artifact
                  path: ./_site

            - name: Deploy to GitHub Pages
              uses: actions/gh-pages@v3
              with:
                  build_dir: _site
